import { Tag } from "./typings/interfaces";

export const JSON_DATA_VERSION = "3";
export const DATA_TAGS: Tag[] = ["Written Notes", "Assignments", "Video Lecture(s)"];
export const FUNNY_TOPICS = [
	"Discrete Computational Nanotech",
	"Quad-Matrix Theory",
	"AIBlockchainNFTs",
	"How To Google",
	"Intro to Stack Overflow",
];
export const CLASS_TAGS: Tag[] = [
	"Programming Languages",
	"Compilers",
	"Security",
	"Systems",
	"Machine Learning",
	"Introduction",
	"Theory",
	"Graphics",
	"Application Development",
	"Game",
	"Algorithms",
	"Artificial Intelligence",
	"Crypto",
	"Database",
	"Software",
	"Robotics"
];

export const TEXTBOOK_TAGS: Tag[] = [
	"introduction",
	// maths
	"mathematics",
	// "statistics",
	// core
	"algorithms",
	"datastructures",
	"networks",
	"databases",
	"systems",
	"theory",
	// langs
	// "javascript",
	"cprogramming",
	"python",
	"java",
	"web",
	// "flask",
	// "redis",
	// "mongodb",
	// "haskell",
	"rprogramming",
	"matlab",
	"latex",
	// "xml",
	// random
	"machinelearning",
	"crypto",
	// "robotics",
	"graphics",
	// "blender",
	"biology",
	"linux",
	// "knoppix",
	// "security",
	// "xforms",
	"GIS",
	"misc",
];
export const SOURCE_COLORS = {
	cornell: "#B31B1B",
	penn: "#011F5B",
	mit: "#8A8B8C",
	caltech: "#FF6C0C",
	waterloo: "#ffd54f",
	harvard: "#A41034",
	yale: "#0f4d92",
	brown: "#381C00",
	berkeley: "#C4820F",
	fayetteville: "#2E63B6",
	washington: "#363C74",
	uiuc: "#0455A4",
	northeastern: "#D41B2C",
	northwestern: "#4E2A84",
	tufts: "#3E8EDE",
	davis: "#B3A369",
	utah: "#CC0000",
	hunter: "#355E3B",
	princeton: "#FF6000",
	stanford: "#8C1515",
	dartmouth: "#00693e",
	carnegiemellon: "#B71E34",
	columbia: "#9BCBEB",
	rpi: "#D6001C",
	nyu: "#57068c",
	utexas: "#BF5700",
	chicago: "#800000",
	riverside: "#2D6CC0",
	georgiatech: "#B3A369",
	utoronto: "#25355A",
	upitt: "#003594",
	michigan: "#FFCB05",
	tomlooman: "#8C1515",
	jhu: "#68ace5",
	uci: "#FFC72C",
	ucla: "#2774AE",
	bu: "#CC0000",
	bw: "#FFCC33",
};
